# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-03 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='decription',
            new_name='description',
        ),
    ]
